# The keys are the marker ids
OBJECT_DESCRIPTION = {'0':   {'objectName': 'marker_0',
                              'objectType': 'pivot',
                              'length':     5.28},
                      '1':   {'objectName': 'marker_1',
                              'objectType': 'pivot',
                              'length':     5.28},
                      '2':   {'objectName': 'marker_2',
                              'objectType': 'marker',
                              'length':     5.28},
                      '3':   {'objectName': 'pivot_0',
                              'objectType': 'reference',
                              'length':     5.28},
                      '5':   {'objectName': 'pivot_1',
                              'objectType': 'pivot',
                              'length':     5.28},
                      '7':   {'objectName': 'pivot_2',
                              'objectType': 'pivot',
                              'length':     5.28},   
                      '100': {'objectName': 'syringe',
                              'objectType': 'syringe',
                              'length':     2.35,
                              'offset':     {'x': 0.0,
                                             'y': -1.5,
                                             'z': 0.0}},
                      'hmd': {'objectName': 'hmd',
                              'objectType': 'hmd',
                              'offset':     {'x': 6.0,
                                             'y': 0.0,
                                             'z': 0.0}}}