# The keys are the marker ids
OBJECT_DESCRIPTION = {'0':   {'objectName': 'marker_0',
                              'objectType': 'pivot',
                              'length':     5.30},
                      '1':   {'objectName': 'marker_1',
                              'objectType': 'marker',
                              'length':     5.30},
                      '2':   {'objectName': 'marker_2',
                              'objectType': 'marker',
                              'length':     5.30},
                      '3':   {'objectName': 'pivot_3',
                              'objectType': 'reference',
                              'length':     5.30},
                      '4':   {'objectName': 'pivot_4',
                              'objectType': 'pivot',
                              'length':     5.30},
                      '5':   {'objectName': 'pivot_5',
                              'objectType': 'pivot',
                              'length':     5.30},
                      '6':   {'objectName': 'pivot_6',
                              'objectType': 'pivot',
                              'length':     5.30},
                      '7':   {'objectName': 'pivot_7',
                              'objectType': 'pivot',
                              'length':     5.30},
                      '9':   {'objectName': 'arm_9',
                              'objectType': 'arm',
                              'length':     4.45},
                      '10':  {'objectName': 'pivot_10',
                              'objectType': 'pivot',
                              'length':     4.45},
                      '11':  {'objectName': 'pivot_11',
                              'objectType': 'pivot',
                              'length':     4.45},
                      '100': {'objectName': 'syringe_100',
                              'objectType': 'syringe',
                              'length':     2.35,
                              'offset':     {'x': 0.0,
                                             'y': -1.5,
                                             'z': 0.0}},
                      '102': {'objectName': 'syringe_102',
                              'objectType': 'syringe',
                              'length':     2.35},
                      'hmd': {'objectName': 'hmd',
                              'objectType': 'hmd',
                              'offset':     {'x': 6.0,
                                             'y': 0.0,
                                             'z': 0.0}}}